from algorithm_collection.search.linear_search import linear_search
from algorithm_collection.search.linear_search_with_sentinel import linear_search_with_sentinel
from algorithm_collection.search.jump_search import jump_search
from algorithm_collection.search.binary_search import binary_search
from algorithm_collection.search.interpolation_search import interpolation_search
