from algorithm_collection.sort.bubble_sort import bubble_sort
from algorithm_collection.sort.insertion_sort import insertion_sort
from algorithm_collection.sort.selection_sort import selection_sort
from algorithm_collection.sort.bogo_sort import bogo_sort
