from distance_collection.euclidean_distance import euclidean_distance
from distance_collection.cosine_distance import cosine_distance
from distance_collection.canberra_distance import canberra_distance
